apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.service.name }}
  namespace: {{ .Values.elasticsearch.namespace }}
  labels:
    app: {{ .Values.elasticsearch.name }}
    component: elasticsearch
spec:
  type: {{ .Values.elasticsearch.service.type }}
  ports:
  - port: {{ .Values.elasticsearch.service.port }}
    targetPort: {{ .Values.elasticsearch.service.targetPort }}
    protocol: TCP
    name: http
  - port: 9300
    targetPort: 9300
    protocol: TCP
    name: transport
  selector:
    app: {{ .Values.elasticsearch.name }}