apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.logstash.service.name }}
  namespace: {{ .Values.logstash.namespace }}
  labels:
    app: {{ .Values.logstash.name }}
    component: logstash
spec:
  type: {{ .Values.logstash.service.type }}
  ports:
  - port: {{ .Values.logstash.service.port }}
    targetPort: {{ .Values.logstash.service.targetPort }}
    protocol: TCP
    name: beats
  - port: 9600
    targetPort: 9600
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.logstash.name }}
    