{{- if .Values.urlShortener.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.urlShortener.name }}-sa
  namespace: {{ .Values.global.serviceNamespace}}
  labels:
    app: {{ .Values.urlShortener.name }}
{{- end }}
