apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: {{ .Values.kibana.namespace }}
  labels:
    app: {{ .Values.kibana.name }}
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.port: 5601
    elasticsearch.hosts: ["http://{{ .Values.kibana.elasticsearch.host }}:{{ .Values.kibana.elasticsearch.port }}"]
    monitoring.ui.container.elasticsearch.enabled: true