apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.service.name }}
  namespace: {{ .Values.kibana.namespace }}
  labels:
    app: {{ .Values.kibana.name }}
    component: kibana
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
  - port: {{ .Values.kibana.service.port }}
    targetPort: {{ .Values.kibana.service.targetPort }}
    {{- if eq .Values.kibana.service.type "NodePort" }}
    nodePort: {{ .Values.kibana.service.nodePort }}
    {{- end }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.kibana.name }}